### ISSUE TITLE
This repo is what goole gives as "nodejs aba file generator"

### ISSUE THREAD

**Issue by koresar** [JedWatson/aba#1]
Hi @JedWatson 

Recently I was googling for an ABA file generator. This repo is shown top 1 on google. But `npm i aba` won't install this package as README.md says.

So wrote one myself. It's got docs, tests, examples, etc.
https://www.npmjs.com/package/aba-generator
To my knowledge, it's the only JS package which actually works. I couldn't find working alternatives, moreover none has any code examples.

How about we do some good for the Australian developers. I propose:
* Amend this repo README, saying "this module is long deprecated, please use **that** one".

WDYT?

**Comment by JedWatson** [comment]
👍 

Done! Sorry, totally forgot I got halfway through writing this then didn't need it anymore. Happy to redirect at yours.

**Comment by koresar** [comment]
Great! Thank you
